cmake_minimum_required(VERSION 3.14)
project(sidebar-tests LANGUAGES CXX)
set(CMAKE_AUTOMOC ON)
find_package(Qt6 REQUIRED COMPONENTS Core Test)
find_package(KF6Solid REQUIRED)
enable_testing()
add_executable(tst_placesmodel tst_placesmodel.cpp ../model/placesmodel.cpp ../model/placesitem.cpp)
target_link_libraries(tst_placesmodel PRIVATE Qt6::Core Qt6::Test KF6::Solid)
add_test(NAME placesmodel COMMAND tst_placesmodel)
